### PR TITLE
local time: fix the date casting

### PR DESCRIPTION
**Pull request by viezel**
works also in Safari :)

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

**Comment by freekmurze** [comment]
That works in safari, but I notice the calculated time is wrong. This is what is display in my browser.

image


But GMT+2 should be 20:00, not 22:00.

Screenshot 2020-08-26 at 09 11 49

Could you take a look at this?

**Comment by viezel** [comment]
@freekmurze you have forgotten to compile the assets again

**Comment by freekmurze** [comment]
Right! On it 🙂

**Comment by freekmurze** [comment]
Working perfectly now, thanks!

**Pull request merged**
