### PR TITLE
it display addition info field's error message and old data

### PR DESCRIPTION
**Pull request by rahulkhimsuriya**
### Repopulating additional info. field with it's data instead of abstract field.

### CODE REVIEW

**Comment by freekmurze** [comment]
Due to code formatting it's very hard to see in the diff what your actual changes are. 

Could you revert all code formatting and only PR the bare minimum changes?

**Comment by rahulkhimsuriya** [comment]
Okay.
let me do that.

**Comment by rahulkhimsuriya** [comment]
@freekmurze can you check now ?

**Comment by freekmurze** [comment]
Much better, thanks!

**Pull request merged**
